### ISSUE TITLE
Control the AuidiBot

### ISSUE THREAD

**Issue by ffatihkocc** [robustify/audibot#2]
Did you have teleop file this model or how can i control the car model?

**Comment by robustify** [comment]
To control audibot, another ROS node needs to continuously publish the steering, brake, and throttle command topics shown in the README. There are no nodes to do that in this repository; its purpose is to be a generic simulator that can be used for many different simulation scenarios.

**Comment by prodaa1234** [comment]
Hi! I tried to publish the the steering, brake, and throttle command topics, but the audibot doesn't move. Could you help me with an example of code or could I show you my code so you could tell me what is wrong with him?
Thank you!

**Comment by ffatihkocc** [comment]
Hi, ı handle it your problem. If you share your source code ı'll try to help you

**Comment by prodaa1234** [comment]
This is my code :

```
#!/usr/bin/python
import rospy
import time
import math

from std_msgs.msg import Float64
from std_msgs.msg import UInt8

from geometry_msgs.msg import TwistStamped

steering_cmd =-0.5
brake_cmd =100
throttle_cmd=1
gear_cmd=0
 
def start_stop():
    #start
    cmd_steering=Float64()
    cmd_steering=steering_cmd
    cmd_brake=Float64()
    cmd_brake=brake_cmd
    cmd_throttle=Float64()
    cmd_throttle=throttle_cmd
    cmd_gear=UInt8()
    cmd_gear=gear_cmd

    twist=TwistStamped()
    rate=rospy.Rate(10)
    while not rospy.is_shutdown():
        publisher1.publish(cmd_steering) #start and go
        publisher2.publish(cmd_brake) 
        publisher3.publish(cmd_throttle)
        publisher4.publish(cmd_gear)
        rate.sleep()

def twistCallback(data):
    Print("subscriber Twist:")
    print(data)

if __name__ == '__main__':
    try:
        #create publisher node
        rospy.init_node('start_publisher',anonymous=True)
        publisher1=rospy.Publisher('steering_cmd',Float64,queue_size=5)
        publisher2=rospy.Publisher('brake_cmd',Float64,queue_size=5)
        publisher3=rospy.Publisher('throttle_cmd',Float64,queue_size=5)
        publisher4=rospy.Publisher('gear_cmd',UInt8,queue_size=5)
        subscriber = rospy.Subscriber('twist', TwistStamped, twistCallback)
        #use the function
        start_stop()
    except rospy.ROSInterruptException:
        rospy.loginfo("node terminated.")
```

**Comment by robustify** [comment]
The brakes have precedence over the throttle. Because you're sending 100 Nm of brake torque command, it is not applying the 100% throttle. Also, in your `twistCallback()` function, you have a syntax error. There shouldn't be a capital 'P' in `print`.

Other than that, your program is working correctly.

**Comment by prodaa1234** [comment]
I made the changes, but the audibot is not moving yet. I run in the terminal "roslaunch audibot_gazebo single_vehicle_example.launch " and "rosrun audibot_gazebo start.py " (start.py is my file). Should I do something else?

**Comment by robustify** [comment]
Hi @prodaa1234,

I ran the program you pasted above, and the car applied a nonzero throttle and accelerated when I changed your brake command to zero. If there is any nonzero brake command, the vehicle will give precedence to that and ignore the throttle.

**Comment by prodaa1234** [comment]
It's working. Thank you very much!
