### ISSUE TITLE
ROS2 branch not compiling or working

### ISSUE THREAD

**Issue by alalemp** [robustify/audibot#8]
Thanks for the nice package, have been using it to teach in my class. Corrected all the missing elements for ROS2. Appreciate if you can accept the pull requested. Tested on ROS2 Iron.

**Comment by robustify** [comment]
Thanks for the help addressing the ROS 2 issues! #7  fixes and improves the ROS 2 implementation. Tested in both ROS 2 Humble and Iron, but ROS 2 Foxy no longer works because of the `tf2_geometry_msgs.hpp` file. Only `tf2_geometry_msgs.h` exists in ROS 2 Foxy
